export const GET_PRODUCTS_LOAD = "GET_PRODUCTS_LOAD";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCT = "GET_PRODUCT";



